// AUTO-GENERATED by scripts/gen-examples.mjs — do not edit by hand.
import type { RawExample } from "./types";
import ex_barley_morris_anomaly from "./datasets/barley-morris-anomaly.json";
import ex_car_profiles_by_origin from "./datasets/car-profiles-by-origin.json";
import ex_cars_horsepower_vs_mpg from "./datasets/cars-horsepower-vs-mpg.json";
import ex_co2_emitters_treemap from "./datasets/co2-emitters-treemap.json";
import ex_co2_mauna_loa from "./datasets/co2-mauna-loa.json";
import ex_co2_per_capita_1990_vs_now from "./datasets/co2-per-capita-1990-vs-now.json";
import ex_co2_seasonal_cycle from "./datasets/co2-seasonal-cycle.json";
import ex_crecimiento_pib_peru from "./datasets/crecimiento-pib-peru.json";
import ex_daily_steps_2025 from "./datasets/daily-steps-2025.json";
import ex_disaster_deaths_by_decade from "./datasets/disaster-deaths-by-decade.json";
import ex_ecommerce_checkout_funnel from "./datasets/ecommerce-checkout-funnel.json";
import ex_electricity_mix_by_country from "./datasets/electricity-mix-by-country.json";
import ex_freelancer_monthly_budget from "./datasets/freelancer-monthly-budget.json";
import ex_gapminder_families_and_lifespans from "./datasets/gapminder-families-and-lifespans.json";
import ex_global_plastic_production from "./datasets/global-plastic-production.json";
import ex_imdb_rating_by_genre from "./datasets/imdb-rating-by-genre.json";
import ex_imdb_rating_distribution from "./datasets/imdb-rating-distribution.json";
import ex_inflacion_lima from "./datasets/inflacion-lima.json";
import ex_internet_america_latina from "./datasets/internet-america-latina.json";
import ex_iowa_electricity_shift from "./datasets/iowa-electricity-shift.json";
import ex_life_expectancy_continents from "./datasets/life-expectancy-continents.json";
import ex_matriz_electrica_peru from "./datasets/matriz-electrica-peru.json";
import ex_pib_per_capita_latam from "./datasets/pib-per-capita-latam.json";
import ex_presidentes_peru_2016_2025 from "./datasets/presidentes-peru-2016-2025.json";
import ex_q3_okr_progress from "./datasets/q3-okr-progress.json";
import ex_saas_arr_bridge from "./datasets/saas-arr-bridge.json";
import ex_saas_monthly_kpis from "./datasets/saas-monthly-kpis.json";
import ex_seattle_2015_heat_calendar from "./datasets/seattle-2015-heat-calendar.json";
import ex_seattle_monthly_rainfall from "./datasets/seattle-monthly-rainfall.json";
import ex_seattle_temperature_by_month from "./datasets/seattle-temperature-by-month.json";
import ex_seattle_weather_mix from "./datasets/seattle-weather-mix.json";
import ex_solar_capacity_leaders from "./datasets/solar-capacity-leaders.json";
import ex_solar_module_prices from "./datasets/solar-module-prices.json";
import ex_solar_share_of_electricity from "./datasets/solar-share-of-electricity.json";
import ex_sp500_lost_decade from "./datasets/sp500-lost-decade.json";
import ex_tech_stocks_2000s from "./datasets/tech-stocks-2000s.json";
import ex_us_age_structure_1900_2000 from "./datasets/us-age-structure-1900-2000.json";
import ex_us_unemployment_by_industry from "./datasets/us-unemployment-by-industry.json";
import ex_wealth_and_health from "./datasets/wealth-and-health.json";
import ex_wind_solar_decade from "./datasets/wind-solar-decade.json";
import ex_world_electricity_mix from "./datasets/world-electricity-mix.json";
import ex_world_primary_energy from "./datasets/world-primary-energy.json";

export const RAW_EXAMPLES: RawExample[] = [
  ex_barley_morris_anomaly as RawExample,
  ex_car_profiles_by_origin as RawExample,
  ex_cars_horsepower_vs_mpg as RawExample,
  ex_co2_emitters_treemap as RawExample,
  ex_co2_mauna_loa as RawExample,
  ex_co2_per_capita_1990_vs_now as RawExample,
  ex_co2_seasonal_cycle as RawExample,
  ex_crecimiento_pib_peru as RawExample,
  ex_daily_steps_2025 as RawExample,
  ex_disaster_deaths_by_decade as RawExample,
  ex_ecommerce_checkout_funnel as RawExample,
  ex_electricity_mix_by_country as RawExample,
  ex_freelancer_monthly_budget as RawExample,
  ex_gapminder_families_and_lifespans as RawExample,
  ex_global_plastic_production as RawExample,
  ex_imdb_rating_by_genre as RawExample,
  ex_imdb_rating_distribution as RawExample,
  ex_inflacion_lima as RawExample,
  ex_internet_america_latina as RawExample,
  ex_iowa_electricity_shift as RawExample,
  ex_life_expectancy_continents as RawExample,
  ex_matriz_electrica_peru as RawExample,
  ex_pib_per_capita_latam as RawExample,
  ex_presidentes_peru_2016_2025 as RawExample,
  ex_q3_okr_progress as RawExample,
  ex_saas_arr_bridge as RawExample,
  ex_saas_monthly_kpis as RawExample,
  ex_seattle_2015_heat_calendar as RawExample,
  ex_seattle_monthly_rainfall as RawExample,
  ex_seattle_temperature_by_month as RawExample,
  ex_seattle_weather_mix as RawExample,
  ex_solar_capacity_leaders as RawExample,
  ex_solar_module_prices as RawExample,
  ex_solar_share_of_electricity as RawExample,
  ex_sp500_lost_decade as RawExample,
  ex_tech_stocks_2000s as RawExample,
  ex_us_age_structure_1900_2000 as RawExample,
  ex_us_unemployment_by_industry as RawExample,
  ex_wealth_and_health as RawExample,
  ex_wind_solar_decade as RawExample,
  ex_world_electricity_mix as RawExample,
  ex_world_primary_energy as RawExample,
];
